export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';

export const POST_FEEDBACK_REQUEST = 'POST_FEEDBACK_REQUEST';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';
export const POST_FEEDBACK_FAILURE = 'POST_FEEDBACK_FAILURE';

export const SELECT_IMAGE = 'SELECT_IMAGE';
export const IMAGE_LOADED = 'IMAGE_LOADED';